package n0Nob8PjUDvjS3MA1laYEKgg2KhpHyRdg4EJbcTJwJWDw9GkhhD6fHSYFBxa;

import android.view.ViewConfiguration;

public abstract class uKo7OCHL2lMivEF7eLsPf5oYebQSCeIRWH {
    public static final float P6WU5Fb80VNGO5Et4Io8BBRMy5iYWzEMiOWjFQ6aC1H5bM4J2Re3zDKrWeh8bMHmbdtoHUf6AF0k9EVEcdtch1VlBNZCDNBHyq8pJxCnCnBKiHKrl8ianGdd8GWwoH0w5UEx6qiiTrAdRWvKBvkoKS24HXJp2d = ViewConfiguration.getScrollFriction();
}
