package BE8JVrulQ7ijGztmAfDOtVT5YsrSogoWMTVkIaE0OkQ8wAF1jp6ASCcLAIcyXFwkObQduU4gkPUUXsxo99jIVxO0ZQMDqodZWUexvtAepDoWsMH3AfX91fDYPrZVDGYzU7jFKF3n1KKXCyuE;

import D2SFNPT8hkiEzkQZZpQFcEpmofd4OOY3valAWANeTShzJVwwwkLuclzSNaWqKq8Poet5LeRMVje5Qh6K1I8LcEAYcIJJilbU5GqLq3ayB.oQihSwLqd0g1qHMxAej6id7aYVUnpbxuEKRkhjwJDibJQxBBNor3YJDepREGWtZc0FHtpBDqOzhyoDTYB3IuPeq6GaWZDWy2iMz;
import android.graphics.RenderEffect;
import android.graphics.RenderNode;

public final class CrcgYjUnADF4tCPCilou2kJjqgraYIJeNY3htrxvXe59wkjMJwYctVZhCWnSMCPyFOW1vAXqyIvrRaZwNw1wP2obaCRRD {
    public static final CrcgYjUnADF4tCPCilou2kJjqgraYIJeNY3htrxvXe59wkjMJwYctVZhCWnSMCPyFOW1vAXqyIvrRaZwNw1wP2obaCRRD P6WU5Fb80VNGO5Et4Io8BBRMy5iYWzEMiOWjFQ6aC1H5bM4J2Re3zDKrWeh8bMHmbdtoHUf6AF0k9EVEcdtch1VlBNZCDNBHyq8pJxCnCnBKiHKrl8ianGdd8GWwoH0w5UEx6qiiTrAdRWvKBvkoKS24HXJp2d = new Object();

    public final void P6WU5Fb80VNGO5Et4Io8BBRMy5iYWzEMiOWjFQ6aC1H5bM4J2Re3zDKrWeh8bMHmbdtoHUf6AF0k9EVEcdtch1VlBNZCDNBHyq8pJxCnCnBKiHKrl8ianGdd8GWwoH0w5UEx6qiiTrAdRWvKBvkoKS24HXJp2d(RenderNode renderNode, oQihSwLqd0g1qHMxAej6id7aYVUnpbxuEKRkhjwJDibJQxBBNor3YJDepREGWtZc0FHtpBDqOzhyoDTYB3IuPeq6GaWZDWy2iMz oqihswlqd0g1qhmxaej6id7ayvunpbxuekrkhjwjdibjqxbbnor3yjdepregwtzc0fhtpbdqozhyodtyb3iupeq6gawzdwy2imz) {
        renderNode.setRenderEffect((RenderEffect) null);
    }
}
